version: "3"

services:
  flask_api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:                                                                                                                                                                                                                                  
      - "7999:7999"
